import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createBlankDictionary, evaluateBlankBoard, applyBlankSwap, replayBlankSession } from '../engine/swap-blank.mjs';
import { solveBlankExact } from '../engine/swap-blank-solver.mjs';
const read = path => readFile(new URL(`../${path}`, import.meta.url));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
test('single private blank day binds exact proof, licensed words and displaced ordinary recovery', async () => {
  const raw = await read('data/swap-blank/puzzles.json'), puzzles = JSON.parse(raw);
  const wordsRaw = await read('data/swap-blank/words.json'), vocabulary = JSON.parse(wordsRaw);
  const manifest = JSON.parse(await read('data/swap-blank/manifest.json'));
  assert.equal(puzzles.length, 1); assert.equal(vocabulary.words.length, 11395);
  assert.equal(hash(raw), manifest.corpusSha256); assert.equal(hash(wordsRaw), manifest.dictionarySha256);
  assert.deepEqual(wordsRaw, await read(`public/data/swap-words-${vocabulary.version}.json`));
  assert.equal(typeof vocabulary.copyright, 'string'); assert.ok(vocabulary.copyright.length > 1000);
  const puzzle = puzzles[0], dictionary = createBlankDictionary(vocabulary.words);
  assert.equal(puzzle.rulesVersion, 'swap-blank-v1'); assert.equal(puzzle.dictionaryVersion, vocabulary.version);
  assert.equal(puzzle.letters.filter(tile => tile === ' ').length, 1);
  assert.ok(evaluateBlankBoard(puzzle.letters, dictionary).runs.every(run => !run.admitted));
  const demos = JSON.parse(await read('docs/research/blank-prototype-fixtures.json')).fixtures;
  assert.ok(demos.every(fixture => fixture.board.join('') !== puzzle.letters.join('')));
  const proof = solveBlankExact(puzzle.letters, vocabulary.words);
  assert.equal(proof.status, 'PROVEN'); assert.ok(proof.minimum >= 3);
  assert.equal(proof.minimum, puzzle.optimality.minimumMoves);
  assert.equal(proof.certificate.rulesVersion, puzzle.rulesVersion);
  assert.equal(puzzle.optimality.rulesVersion, puzzle.rulesVersion);
  assert.equal(proof.certificate.boardSha256, puzzle.optimality.boardSha256);
  assert.equal(proof.certificate.dictionaryWordsSha256, puzzle.optimality.dictionaryWordsSha256);
  assert.deepEqual(proof.solution.map(action => ({ type: 'swap', ...action })), puzzle.optimality.optimalActions);
  let board = puzzle.letters, movedBlank = false;
  for (const action of proof.solution) { movedBlank ||= board[action.from] === ' ' || board[action.to] === ' '; board = applyBlankSwap(board, action); }
  assert.equal(movedBlank, true);
  const result = replayBlankSession(puzzle.letters, puzzle.optimality.optimalActions, dictionary);
  assert.equal(result.won, true); assert.deepEqual(result.words, puzzle.optimality.optimalWords);
  const recovery = manifest.displacedOrdinary, ordinaryRaw = await read(recovery.path);
  assert.equal(hash(ordinaryRaw), recovery.corpusSha256);
  assert.equal('puzzle' in recovery, false);
  assert.equal(hash(JSON.stringify(JSON.parse(ordinaryRaw).find(p => p.id === recovery.id))), recovery.puzzleSha256);
});
