import {createBlankDictionary,replayBlankSession,evaluateBlankBoard,applyBlankSwap} from './swap-blank.mjs';
const el=id=>document.getElementById(id),message=text=>el('message').textContent=text;
let fixture,dictionary,actions=[],selected=null,step=0;
const state=()=>replayBlankSession(fixture.board,actions,dictionary);
function paint(target,board,runs,interactive=false){const green=new Set(runs.filter(r=>r.valid).flatMap(r=>r.indices));target.replaceChildren();board.forEach((letter,i)=>{const tile=document.createElement(interactive?'button':'span');tile.className=`tile${green.has(i)?' valid':''}${interactive&&selected===i?' selected':''}`;tile.textContent=letter;tile.setAttribute('aria-label',`${letter===' '?'Blank':letter}, row ${Math.floor(i/5)+1}, column ${i%5+1}${green.has(i)?', valid word':''}`);if(interactive){tile.id=`tile-${i}`;tile.setAttribute('aria-pressed',String(selected===i));if(selected!==null&&Math.abs(Math.floor(selected/5)-Math.floor(i/5))+Math.abs(selected%5-i%5)===1&&board[selected]!==letter){tile.classList.add('partner');tile.setAttribute('aria-label',tile.getAttribute('aria-label')+', available to swap');}tile.onclick=()=>select(i);}target.append(tile);if(i%5===4){const summary=document.createElement('span');summary.className='row-check';summary.textContent=`Row ${Math.floor(i/5)+1}: `+runs.filter(r=>r.row===Math.floor(i/5)).map(r=>`${r.word.toUpperCase()}: ${r.valid?'counts':'not a distinct word'}`).join(', ');target.append(summary);}});}
function render(){const s=state(),focus=document.activeElement?.id;paint(el('tiles'),s.board,s.runs,true);for(const tile of el('tiles').querySelectorAll('button'))tile.disabled=s.won;document.querySelector('.intro p').classList.toggle('solved',s.won);el('moves').textContent=`${s.won?'Yours ':''}${s.moves} swaps`;el('undo').disabled=s.won||!s.undoDepth;el('reset').disabled=s.won||!actions.length;el('result').hidden=!s.won;el('headline').textContent=s.won?(s.moves===fixture.proof.minimum?"Perfect. Couldn't use fewer swaps.":'Nicely swapped.'):'One blank. More ways to solve.';el('minimum').textContent=`Best possible ${fixture.proof.minimum}`;document.getElementById(focus)?.focus({preventScroll:true});}
function select(i){if(state().won)return;if(selected===null){selected=i;render();message('Choose a neighboring tile.');return;}if(selected===i){selected=null;render();return;}try{const before=state().board,next=applyBlankSwap(before,{from:selected,to:i});if(next.join('')===before.join('')){message('Those tiles are the same. Choose a different tile.');return;}actions.push({type:'swap',from:selected,to:i});selected=null;render();const s=state();message(s.won?'Nicely swapped.':s.runs.map(r=>`${r.word.toUpperCase()}: ${r.valid?'counts':'not a distinct word'}`).join('. '));}catch{message('Choose a neighboring tile.');}}
el('undo').onclick=()=>{actions.push({type:'undo'});selected=null;render();message('Swap undone. Your count stays.');};el('reset').onclick=()=>{actions.push({type:'reset'});selected=null;render();message('Board reset. Your count stays.');};el('retry').onclick=()=>{actions=[];selected=null;render();message('Same board. Try a different route.');};
el('help').onclick=()=>el('help-dialog').showModal();document.querySelectorAll('dialog .close').forEach(button=>button.onclick=()=>button.closest('dialog').close());el('theme').onclick=()=>{const dark=document.body.classList.toggle('dark');el('theme').setAttribute('aria-label',dark?'Use light theme':'Use dark theme');el('logo').src=`/assets/jumble-logo-v3${dark?'-dark':''}-720.webp`;};
function solution(){let board=[...fixture.board];for(const action of fixture.proof.solution.slice(0,step))board=applyBlankSwap(board,action);paint(el('solution-tiles'),board,evaluateBlankBoard(board,dictionary).runs);const next=fixture.proof.solution[step],name=i=>`${board[i]===' '?'blank':board[i]} at row ${Math.floor(i/5)+1}, column ${i%5+1}`;el('step').textContent=`Step ${step} of ${fixture.proof.minimum}. ${next?`Swap ${name(next.from)} with ${name(next.to)}.`:evaluateBlankBoard(board,dictionary).words.join(' · ')}`;el('previous').disabled=step===0;el('next').disabled=step===fixture.proof.minimum;}
el('solution').onclick=()=>{step=0;solution();el('solution-dialog').showModal();};el('previous').onclick=()=>{step--;solution();};el('next').onclick=()=>{step++;solution();};
document.addEventListener('keydown',e=>{if(!fixture||document.querySelector('dialog[open]')||!e.target.id.startsWith('tile-'))return;const i=Number(e.target.id.slice(5));let n=i;if(e.key==='ArrowLeft'&&i%5)n--;else if(e.key==='ArrowRight'&&i%5<4)n++;else if(e.key==='ArrowUp'&&i>=5)n-=5;else if(e.key==='ArrowDown'&&i<10)n+=5;else if(e.key==='Escape'){selected=null;render();return;}else return;e.preventDefault();el(`tile-${n}`).focus();});
try{const [vocabulary,examples]=await Promise.all(['/prototype/words.json','/prototype/fixtures.json'].map(async path=>{const r=await fetch(path);if(!r.ok)throw Error('Prototype unavailable.');return r.json();}));dictionary=createBlankDictionary(vocabulary.words);fixture=examples.fixtures.find(f=>f.id===(new URLSearchParams(location.search).get('fixture')||'moving-blank'));if(!fixture||fixture.proof.status!=='PROVEN')throw Error('This example has no exact proof.');const witness=replayBlankSession(fixture.board,fixture.proof.solution.map(a=>({...a,type:'swap'})),dictionary);if(!witness.won||witness.moves!==fixture.proof.minimum)throw Error('This example could not be verified.');render();message('');}catch(error){message(error.message);}
