import { summarizeHistory, todayLinkVisible } from './results.js';
import { normalizeBoard, replaySwapSession } from '../engine/swap.mjs';
const MODE = 'swap-v1';
type Action = {type:'swap';from:number;to:number}|{type:'undo'}|{type:'reset'};
type Puzzle = {id:string;mode:string;board:string[];dictionaryVersion:string;preview?:string};
type Result = {puzzleId:string;mode:string;words:string[];moves:number;rank:number;total:number;tied:number;actions:Action[]};
type Save = {version:1;mode:string;puzzleId:string;dictionaryVersion:string;initialBoard:string;actions:Action[]};
const el = <T extends HTMLElement = HTMLElement>(id:string) => document.getElementById(id) as T;
const message=(text:string)=>{el('message').textContent=text;};
const storage={get(key:string){try{return localStorage.getItem(key);}catch{return null;}},set(key:string,value:string){try{localStorage.setItem(key,value);}catch{message('Storage is unavailable. Keep this tab open to save your progress.');}}};
async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(`/api/${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(response.status===204)return undefined as T;if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Jumble could not connect. Please try again.');const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error||'Could not connect. Please try again.'),{code:data.code});return data;}
const track=(name:string)=>{void api('event',{name,mode:MODE}).catch(()=>{});};
let puzzle:Puzzle,save:Save,dictionary:Set<string>,selected:number|null=null,result:Result|undefined,sessionId:string|undefined,sessionRequest:Promise<void>|undefined,submitting=false,animating=false;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const state=()=>replaySwapSession(puzzle.board,save.actions,dictionary);
const saveKey=()=>`jumble:${MODE}:${puzzle.id}`;
function persist(){storage.set(saveKey(),JSON.stringify(save));}
function ensureSession(){if(sessionId)return Promise.resolve();if(!sessionRequest)sessionRequest=api<{sessionId:string}>('session',{puzzleId:puzzle.id,mode:MODE}).then(data=>{sessionId=data.sessionId;}).finally(()=>{sessionRequest=undefined;});return sessionRequest;}
function render(){const current=state(),focused=document.activeElement instanceof HTMLElement?document.activeElement.id:'';const board=el('tiles');board.replaceChildren();for(let row=0;row<3;row++){for(let col=0;col<5;col++){const i=row*5+col,button=document.createElement('button');const legal=selected!==null&&selected!==i&&(Math.floor(selected/5)===row||selected%5===col)&&current.board[selected]!==current.board[i];button.id=`tile-${i}`;button.className=`tile${current.validRows[row]?' valid':''}${selected===i?' selected':''}${legal?' partner':''}`;button.textContent=current.board[i];button.disabled=current.won;button.setAttribute('aria-pressed',String(selected===i));button.setAttribute('aria-label',`${current.board[i]}, row ${row+1}, column ${col+1}${current.validRows[row]?', valid word':''}${selected===i?', selected':legal?', available to swap':''}`);button.onclick=()=>void selectTile(i);board.append(button);}const check=document.createElement('span');check.className='row-check';check.textContent=current.validRows[row]?`Row ${row+1} is a word.`:'';check.setAttribute('aria-label',current.validRows[row]?`Row ${row+1}: ${current.rows[row]}, valid`:`Row ${row+1}: not a distinct word`);board.append(check);}el('moves').textContent=`${current.moves} swap${current.moves===1?'':'s'}`;el<HTMLButtonElement>('undo').disabled=current.won||!current.undoDepth;el<HTMLButtonElement>('reset').disabled=current.won||!save.actions.length;el('result').hidden=!current.won;const streak=summarizeHistory(history(),new Date().toISOString().slice(0,10)).current;el('streak').textContent=streak?`${streak} day${streak===1?'':'s'} in a row on this device`:'';document.querySelector('.intro p')?.classList.toggle('solved',current.won);el('headline').textContent=current.won?'Three words. Nicely done.':'Make three words.';el<HTMLButtonElement>('replay').disabled=submitting;el('rank').textContent=result?`Best: ${result.moves} swaps · rank ${result.rank} of ${result.total} at submission${result.tied>1?` · ${result.tied} tied`:''}`:submitting?'Verifying your solve…':'Solved here. Online ranking is not verified yet.';if(focused)document.getElementById(focused)?.focus({preventScroll:true});}
async function selectTile(index:number){if(!puzzle||animating||state().won)return;if(selected===null){selected=index;render();message('Choose a tile in the same row or column.');return;}if(selected===index){selected=null;render();message('');return;}const from=selected,previous=state(),before=previous.board;if(Math.floor(from/5)!==Math.floor(index/5)&&from%5!==index%5){message('Choose a tile in the same row or column.');return;}if(before[from]===before[index]){message('Those letters are the same. Choose a different letter.');return;}if(save.actions.length>=1000){message('This attempt has reached its 1,000-action limit. Your progress is saved.');return;}const a=el(`tile-${from}`).getBoundingClientRect(),b=el(`tile-${index}`).getBoundingClientRect();save.actions.push({type:'swap',from,to:index});selected=null;persist();render();void ensureSession().catch(error=>message(error.message));if(!reducedMotion.matches){animating=true;const animations=[el(`tile-${from}`).animate([{transform:`translate(${b.x-a.x}px,${b.y-a.y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'}),el(`tile-${index}`).animate([{transform:`translate(${a.x-b.x}px,${a.y-b.y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'})];const after=state();for(let row=0;row<3;row++)if(after.validRows[row]&&!previous.validRows[row])for(let col=0;col<5;col++)animations.push(el(`tile-${row*5+col}`).animate([{scale:'1'},{scale:'1.055'},{scale:'1'}],{duration:180,delay:160,easing:'ease-out'}));await Promise.allSettled(animations.map(animation=>animation.finished));animating=false;}const current=state();message(current.won?'':`${current.validRows.filter(Boolean).length} of 3 rows are words.`);if(current.won){recordHistory();el('share').focus({preventScroll:true});void submit();}}
function act(type:'undo'|'reset'){if(!puzzle||animating||state().won||save.actions.length>=1000)return;save.actions.push({type});selected=null;persist();render();message(type==='undo'?'Swap undone. Your count stays.':'Board reset. Your count stays.');if(type==='reset')track('puzzle_reset');el('tile-0').focus({preventScroll:true});}
el('undo').onclick=()=>act('undo');el('reset').onclick=()=>el<HTMLDialogElement>('reset-dialog').showModal();el('reset-confirm').onclick=()=>{el<HTMLDialogElement>('reset-dialog').close();act('reset');};
el('replay').onclick=()=>{if(submitting)return;save.actions=[];result=undefined;selected=null;persist();render();message('Same board. Try a different route.');el('tile-0').focus({preventScroll:true});};
async function submit(){if(!state().won||submitting)return;submitting=true;el('retry-submit').hidden=true;render();try{await ensureSession();result=await api<Result>('result',{mode:MODE,puzzleId:puzzle.id,sessionId,dictionaryVersion:puzzle.dictionaryVersion,actions:save.actions});if(result.mode!==MODE||result.puzzleId!==puzzle.id)throw Error('The result could not be verified.');}catch(error){message(error instanceof Error?error.message:'Your solve is saved. Try verification again.');el('retry-submit').hidden=false;}finally{submitting=false;render();}}
el('retry-submit').onclick=()=>void submit();el('retry-load').onclick=()=>location.reload();
type HistoryRow={day:string;moves:number;words:string[]};
function history():HistoryRow[]{try{const rows=JSON.parse(storage.get(`jumble:${MODE}:history`)||'[]');return Array.isArray(rows)?rows.filter((r:HistoryRow)=>r&&/^\d{4}-\d{2}-\d{2}$/.test(r.day)&&Number.isSafeInteger(r.moves)&&r.moves>0&&Array.isArray(r.words)&&r.words.length===3&&r.words.every(w=>typeof w==='string'&&/^[a-z]{5}$/.test(w))):[];}catch{return [];}}
function recordHistory(){const current=state(),rows=history(),previous=rows.find(r=>r.day===puzzle.id);if(!previous||current.moves<previous.moves)storage.set(`jumble:${MODE}:history`,JSON.stringify([...rows.filter(r=>r.day!==puzzle.id),{day:puzzle.id,moves:current.moves,words:current.rows}].sort((a,b)=>a.day.localeCompare(b.day))));}
el('history').onclick=()=>{const rows=history();el('history-summary').textContent=rows.length?`${rows.length} solved · ${summarizeHistory(rows,new Date().toISOString().slice(0,10)).current} day streak · ${(rows.reduce((sum,row)=>sum+row.moves,0)/rows.length).toFixed(1)} average swaps`:'Your first solve starts here.';el('history-list').replaceChildren(...rows.slice(-30).reverse().map(row=>{const li=document.createElement('li'),a=document.createElement('a');a.href=`/?mode=${MODE}&day=${encodeURIComponent(row.day)}`;a.textContent=`${row.day} · ${row.moves} swaps`;li.append(a);return li;}));el<HTMLDialogElement>('history-dialog').showModal();};
function challengeUrl(){const url=new URL(location.origin);url.searchParams.set('mode',MODE);url.searchParams.set('day',puzzle.id);return url.href;}
function shareText(){const current=state();return `JUMBLE SWAP ${puzzle.id}\n${current.moves} swaps\n${current.rows.map(word=>el<HTMLInputElement>('reveal-words').checked?word.toUpperCase():'🟩🟩🟩🟩🟩').join('\n')}\n${challengeUrl()}`;}
function updateShare(){el<HTMLTextAreaElement>('share-preview').value=shareText();el<HTMLAnchorElement>('share-x').href=`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText())}`;}
el('share').onclick=()=>{el<HTMLInputElement>('reveal-words').checked=false;updateShare();el('share-status').textContent='';el<HTMLDialogElement>('share-dialog').showModal();};el('reveal-words').onchange=updateShare;
async function copyShare(text:string){try{await navigator.clipboard.writeText(text);el('share-status').textContent='Copied.';track('share');}catch{const area=el<HTMLTextAreaElement>('share-preview');area.value=text;area.focus();area.select();el('share-status').textContent='Select and copy the text above.';}}
el('copy-result').onclick=()=>void copyShare(shareText());el('copy-link').onclick=()=>void copyShare(challengeUrl());el('native-share').onclick=async()=>{try{if(navigator.share){await navigator.share({text:shareText()});track('share');}else await copyShare(shareText());}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))await copyShare(shareText());}};
el('download-result').onclick=()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#faf8f1';ctx.fillRect(0,0,1200,630);ctx.fillStyle='#15212d';ctx.font='bold 48px system-ui';ctx.fillText('JUMBLE SWAP',60,80);ctx.font='30px system-ui';ctx.fillText(`${puzzle.id} · ${state().moves} swaps`,60,140);state().rows.forEach((word,row)=>{for(let col=0;col<5;col++){ctx.fillStyle='#d1ebcf';ctx.fillRect(60+col*70,185+row*75,58,58);if(el<HTMLInputElement>('reveal-words').checked){ctx.fillStyle='#15212d';ctx.fillText(word[col].toUpperCase(),74+col*70,225+row*75);}}});ctx.fillStyle='#15212d';ctx.font='24px system-ui';ctx.fillText(challengeUrl(),60,570,1080);const link=document.createElement('a');link.download=`jumble-swap-${puzzle.id}.png`;link.href=canvas.toDataURL('image/png');link.click();track('share');};
const dark=storage.get('jumble:theme')==='dark'||(!storage.get('jumble:theme')&&matchMedia('(prefers-color-scheme:dark)').matches);document.body.classList.toggle('dark',dark);
function themeName(){const dark=document.body.classList.contains('dark');el('theme').setAttribute('aria-label',dark?'Use light theme':'Use dark theme');el<HTMLImageElement>('logo').src=`/assets/jumble-logo-v3${dark?'-dark':''}-720.webp`;}
themeName();el('theme').onclick=()=>{document.body.classList.toggle('dark');storage.set('jumble:theme',document.body.classList.contains('dark')?'dark':'light');themeName();if(puzzle)track('theme_toggle');};el('help').onclick=()=>el<HTMLDialogElement>('help-dialog').showModal();document.querySelectorAll<HTMLButtonElement>('dialog .close,.close-help').forEach(button=>button.onclick=()=>button.closest('dialog')?.close());
async function openSponsors() {
  el<HTMLDialogElement>('sponsor-dialog').showModal(); track('sponsor_open');
  try {
    const data = await api<{rows:{name:string;url:string;cents:number}[];topCents:number}>('sponsors');
    const wall = el('sponsor-wall'); wall.replaceChildren();
    if (!data.rows.length) wall.textContent = 'Be the first to back Jumble.';
    for (const sponsor of data.rows) {
      const row = document.createElement('article'), name = document.createElement('a');
      name.textContent = `${sponsor.name} · $${(sponsor.cents/100).toFixed(2)}`;
      const url = new URL(sponsor.url);
      if (url.protocol==='https:') { name.href = url.href; name.target = '_blank'; name.rel = 'noopener noreferrer sponsored'; }
      row.append(name); wall.append(row);
    }
    el('takeover-detail').textContent = `Top contribution: $${(data.topCents/100).toFixed(2)}. Checkout calculates the amount to pass it, including your link’s existing credit. Rank can change before payment is confirmed.`;
  } catch (error) { el('sponsor-wall').textContent = error instanceof Error?error.message:'Sponsors could not load.'; }
}
el('sponsors-link').onclick = () => void openSponsors();

el('sponsor-mode').onchange = () => {
  const takeover = el<HTMLSelectElement>('sponsor-mode').value==='takeover';
  el('amount-label').hidden = takeover; el('takeover-detail').hidden = !takeover;
  el<HTMLInputElement>('sponsor-amount').disabled = takeover;
};
el<HTMLFormElement>('sponsor-form').onsubmit = async event => {
  event.preventDefault(); const form = event.currentTarget as HTMLFormElement;
  const button = form.querySelector<HTMLButtonElement>('button[type=submit]')!; button.disabled = true;
  try {
    const data = new FormData(form), mode = data.get('mode');
    const payload = {name:data.get('name'),url:data.get('url'),mode,gameMode:MODE,puzzleId:puzzle.id,returnTo:state().won?'result':'entry',...(mode==='takeover'?{}:{amount:Number(data.get('amount'))*100})};
    const fingerprint = JSON.stringify(payload);
    let pending: {fingerprint:string;submissionId:string}|null = null;
    try { pending = JSON.parse(storage.get('jumble:swap-v1:checkout')||'null'); } catch {}
    if (pending?.fingerprint!==fingerprint || typeof pending.submissionId!=='string') pending = {fingerprint,submissionId:crypto.randomUUID()};
    storage.set('jumble:swap-v1:checkout',JSON.stringify(pending));
    const response = await api<{url:string}>('checkout',{...payload,submissionId:pending.submissionId});
    const destination = new URL(response.url);
    if (destination.protocol!=='https:' || destination.hostname!=='checkout.stripe.com') throw new Error('Checkout returned an unexpected destination.');
    location.assign(destination.href);
  } catch (error) {
    el('sponsor-message').textContent = error instanceof Error?error.message:'Checkout could not start.'; button.disabled = false;
    if (error instanceof Error && 'code' in error && ['SUBMISSION_EXPIRED','CHECKOUT_EXPIRED'].includes(String(error.code))) {
      const restart=document.createElement('button');restart.type='button';restart.textContent='Start a new checkout';
      restart.onclick=()=>{storage.set('jumble:swap-v1:checkout','null');restart.remove();el('sponsor-message').textContent='Ready for a new checkout. Your previous payment status has not changed.';};
      el('sponsor-message').append(restart);
    }
  }
};

document.addEventListener('keydown',event=>{if(!puzzle||document.querySelector('dialog[open]')||event.ctrlKey||event.metaKey||event.altKey)return;const target=event.target;if(!(target instanceof HTMLButtonElement)||!target.id.startsWith('tile-'))return;const i=Number(target.id.slice(5));let next=i;if(event.key==='ArrowLeft'&&i%5>0)next--;else if(event.key==='ArrowRight'&&i%5<4)next++;else if(event.key==='ArrowUp'&&i>=5)next-=5;else if(event.key==='ArrowDown'&&i<10)next+=5;else if(event.key==='Escape'){selected=null;render();message('Selection cleared.');}else return;event.preventDefault();el(`tile-${next}`).focus();});
reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches)document.getAnimations().forEach(animation=>animation.cancel());});
async function boot(){try{const params=new URLSearchParams(location.search),requested=params.get('day');puzzle=await api<Puzzle>(`puzzle?mode=${MODE}${requested?`&day=${encodeURIComponent(requested)}`:''}`);if(puzzle.mode!==MODE)throw Error('This version of Jumble is not available yet.');if(puzzle.preview){el('preview-notice').hidden=false;el('preview-notice').textContent=puzzle.preview==='synthetic-fixture'?'Preview · sample puzzle · local rankings only':'Preview · local rankings only';}puzzle.board=normalizeBoard(puzzle.board);const r=await fetch(`/data/swap-words-${encodeURIComponent(puzzle.dictionaryVersion)}.json`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('The word list could not load. Try again.');const lexicon=await r.json();if(lexicon.version!==puzzle.dictionaryVersion||!Array.isArray(lexicon.words)||!lexicon.words.every((w:unknown)=>typeof w==='string'&&/^[a-z]{5}$/.test(w)))throw Error('The word list could not be verified.');dictionary=new Set(lexicon.words);save={version:1,mode:MODE,puzzleId:puzzle.id,dictionaryVersion:puzzle.dictionaryVersion,initialBoard:puzzle.board.join(''),actions:[]};try{const restored=JSON.parse(storage.get(saveKey())||'null');if(restored?.version===1&&restored.mode===MODE&&restored.puzzleId===puzzle.id&&restored.dictionaryVersion===puzzle.dictionaryVersion&&restored.initialBoard===puzzle.board.join('')&&Array.isArray(restored.actions)){replaySwapSession(puzzle.board,restored.actions,dictionary);save.actions=restored.actions;}}catch{}el('day').textContent=`DAILY · ${puzzle.id}`;el('game').setAttribute('aria-busy','false');render();message('');track('puzzle_view');updateTodayLink();if(state().won)void submit();if(['thanks','cancelled'].includes(params.get('sponsor')||'')){storage.set(`jumble:${MODE}:checkout`,'null');el('sponsor-return').hidden=false;el('sponsor-return').textContent=params.get('sponsor')==='thanks'?'Thanks. Your listing appears after payment confirmation.':'Checkout cancelled. Your board is saved.';}}catch(error){message(error instanceof Error?error.message:'Jumble could not load.');el('retry-load').hidden=false;}}
let rolloverTimer:number;
function updateTodayLink(){clearTimeout(rolloverTimer);el('today-link').hidden=!todayLinkVisible(puzzle.id);rolloverTimer=window.setTimeout(updateTodayLink,86400000-Date.now()%86400000+50);}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&puzzle)updateTodayLink();});
void boot();
