import { summarizeHistory, todayLinkVisible } from './results.js';
import { normalizeBoard, replaySwapSession, applySwap, evaluateBoard } from '../engine/swap.mjs';
import { normalizeBlankBoard, replayBlankSession, applyBlankSwap, evaluateBlankBoard } from '../engine/swap-blank.mjs';
let MODE = 'swap-adjacent-v3';
const blankDay=()=>MODE==='swap-blank-v1';
const EARLIER_MODES = ['swap-adjacent-v2','swap-adjacent-v1'];
type Action = {type:'swap';from:number;to:number}|{type:'undo'}|{type:'reset'};
type Puzzle = {id:string;mode:string;board:string[];dictionaryVersion:string;preview?:string};
type Optimal = {moves:number;actions:{type:'swap';from:number;to:number}[];words:string[]};
type Result = {puzzleId:string;mode:string;words:string[];moves:number;rank:number;total:number;tied:number;actions:Action[];optimal?:Optimal};
type Save = {version:1;mode:string;puzzleId:string;dictionaryVersion:string;initialBoard:string;actions:Action[]};
const el = <T extends HTMLElement = HTMLElement>(id:string) => document.getElementById(id) as T;
const message=(text:string)=>{el('message').textContent=text;el('message').classList.toggle('row-check',text==='Nicely swapped.');};
const storage={get(key:string){try{return localStorage.getItem(key);}catch{return null;}},set(key:string,value:string){try{localStorage.setItem(key,value);}catch{message('Storage is unavailable. Keep this tab open to save your progress.');}}};
async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(`/api/${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(response.status===204)return undefined as T;if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Jumble could not connect. Please try again.');const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error||'Could not connect. Please try again.'),{code:data.code});return data;}
const track=(name:string)=>{void api('event',{name,mode:MODE,puzzleId:puzzle?.id}).catch(()=>{});};
let puzzle:Puzzle,save:Save,dictionary:Set<string>,selected:number|null=null,result:Result|undefined,sessionId:string|undefined,sessionRequest:Promise<void>|undefined,submitting=false,animating=false;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function evaluate(input:string[]){if(blankDay()){const value=evaluateBlankBoard(input,dictionary);return {...value,rows:value.words,validRows:[0,1,2].map(row=>value.runs.some(run=>run.row===row)&&value.runs.filter(run=>run.row===row).every(run=>run.valid)),validTiles:input.map((_,i)=>value.runs.some(run=>run.valid&&run.indices.includes(i))),summaries:[0,1,2].map(row=>value.runs.filter(run=>run.row===row).map(run=>`${run.word.toUpperCase()}: ${run.valid?'counts':'not a distinct word'}`).join(', '))};}const value=evaluateBoard(input,dictionary);return {...value,validTiles:input.map((_,i)=>value.validRows[Math.floor(i/5)]),summaries:value.rows.map((word,i)=>`${word.toUpperCase()}: ${value.validRows[i]?'counts':'not a distinct word'}`)};}
function replay(initial:string[],actions:Action[]){const value=blankDay()?replayBlankSession(initial,actions,dictionary):replaySwapSession(initial,actions,dictionary);return {...value,...evaluate(value.board)};}
const state=()=>replay(puzzle.board,save.actions);
const swap=(board:string[],action:{from:number;to:number})=>blankDay()?applyBlankSwap(board,action):applySwap(board,action);
const letterName=(letter:string)=>letter===' '?'Blank':letter;
const saveKey=()=>`jumble:${MODE}:${puzzle.id}`;
function persist(){storage.set(saveKey(),JSON.stringify(save));}
function ensureSession(){if(sessionId)return Promise.resolve();if(!sessionRequest)sessionRequest=api<{sessionId:string}>('session',{puzzleId:puzzle.id,mode:MODE}).then(data=>{sessionId=data.sessionId;}).finally(()=>{sessionRequest=undefined;});return sessionRequest;}
function render(){const current=state(),focused=document.activeElement instanceof HTMLElement?document.activeElement.id:'';const board=el('tiles');board.replaceChildren();for(let row=0;row<3;row++){for(let col=0;col<5;col++){const i=row*5+col,button=document.createElement('button');const legal=selected!==null&&selected!==i&&(Math.abs(Math.floor(selected/5)-row)+Math.abs(selected%5-col)===1);button.id=`tile-${i}`;button.className=`tile${current.validTiles[i]?' valid':''}${selected===i?' selected':''}${legal?' partner':''}`;button.textContent=current.board[i];button.disabled=current.won;button.setAttribute('aria-pressed',String(selected===i));button.setAttribute('aria-label',`${letterName(current.board[i])}, row ${row+1}, column ${col+1}${current.validTiles[i]?', valid word':''}${selected===i?', selected':legal?', available to swap':''}`);button.onclick=()=>void selectTile(i);board.append(button);}const check=document.createElement('span');check.className='row-check';check.textContent=`Row ${row+1}: ${current.summaries[row]}`;board.append(check);}el('moves').textContent=`${current.won?'Yours ':''}${current.moves} swap${current.moves===1?'':'s'}`;el<HTMLButtonElement>('undo').disabled=current.won||!current.undoDepth;el<HTMLButtonElement>('reset').disabled=current.won||!save.actions.length;el('view-result').hidden=!current.won||animating;document.querySelector<HTMLElement>('.intro')!.hidden=current.won;el('headline').textContent=blankDay()?'One blank. More ways to solve.':'Make three words.';el('result-heading').textContent=result?.optimal&&current.moves===result.optimal.moves?'Perfectly swapped.':'Nicely swapped.';el('result-moves').textContent=`${current.moves} swap${current.moves===1?'':'s'}`;el<HTMLButtonElement>('replay').disabled=submitting;el('replay').hidden=!current.won;el('rank').textContent=puzzle.preview?'Unranked preview':result?`${result.moves!==current.moves?`Your best: ${result.moves} swaps · `:''}Daily best rank ${result.rank} of ${result.total} player${result.total===1?'':'s'}${result.tied>1?` · ${result.tied} tied`:''} · at verification`:submitting?'Checking your result…':'Your solve is saved. Retry verification.';el('minimum').textContent=result?.optimal?`Best possible: ${result.optimal.moves} · ${current.moves===result.optimal.moves?'Minimum matched':`${current.moves-result.optimal.moves} above best`}`:'Minimum not verified';el('show-solution').hidden=!result?.optimal;if(focused)document.getElementById(focused)?.focus({preventScroll:true});}
async function selectTile(index:number){if(!puzzle||animating||state().won)return;if(selected===null){selected=index;render();message('');return;}if(selected===index){selected=null;render();message('');return;}const from=selected,previous=state(),before=previous.board;if(Math.abs(Math.floor(from/5)-Math.floor(index/5))+Math.abs(from%5-index%5)!==1){message('Choose a neighboring tile.');return;}if(before[from]===before[index]){selected=null;render();message('Same letters. No swap used.');if(!reducedMotion.matches)for(const i of [from,index])el(`tile-${i}`).animate([{scale:'1'},{scale:'0.95'},{scale:'1'}],{duration:160});return;}if(save.actions.length>=1000){message('This attempt has reached its 1,000-action limit. Your progress is saved.');return;}const a=el(`tile-${from}`).getBoundingClientRect(),b=el(`tile-${index}`).getBoundingClientRect();save.actions.push({type:'swap',from,to:index});selected=null;animating=!reducedMotion.matches;persist();render();void ensureSession().catch(error=>message(error.message));if(!reducedMotion.matches){animating=true;const animations=[el(`tile-${from}`).animate([{transform:`translate(${b.x-a.x}px,${b.y-a.y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'}),el(`tile-${index}`).animate([{transform:`translate(${a.x-b.x}px,${a.y-b.y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'})];const after=state();for(let row=0;row<3;row++)if(after.validRows[row]&&!previous.validRows[row])for(let col=0;col<5;col++)animations.push(el(`tile-${row*5+col}`).animate([{scale:'1'},{scale:'1.055'},{scale:'1'}],{duration:180,delay:160,easing:'ease-out'}));await Promise.allSettled(animations.map(animation=>animation.finished));animating=false;}const current=state();if(current.won)render();message('');if(current.won){recordHistory();openResult(true);void submit();}}
function act(type:'undo'|'reset'){if(!puzzle||animating||state().won||save.actions.length>=1000)return;save.actions.push({type});selected=null;persist();render();message(type==='undo'?'Swap undone. Your count stays.':'Board reset. Your count stays.');if(type==='reset')track('puzzle_reset');el('tile-0').focus({preventScroll:true});}
el('undo').onclick=()=>act('undo');el('reset').onclick=()=>el<HTMLDialogElement>('reset-dialog').showModal();el('reset-confirm').onclick=()=>{el<HTMLDialogElement>('reset-dialog').close();act('reset');};
el('replay').onclick=()=>{if(submitting)return;el<HTMLDialogElement>('result').close();el<HTMLDialogElement>('help-dialog').close();save.actions=[];result=undefined;selected=null;persist();render();message('Same board. Try a different route.');el('tile-0').focus({preventScroll:true});};
async function submit(){if(!state().won||submitting)return;submitting=true;el('retry-submit').hidden=true;render();try{await ensureSession();result=await api<Result>('result',{mode:MODE,puzzleId:puzzle.id,sessionId,dictionaryVersion:puzzle.dictionaryVersion,actions:save.actions});if(result.mode!==MODE||result.puzzleId!==puzzle.id)throw Error('The result could not be verified.');if(result.optimal){try{const optimal=result.optimal,verified=replay(puzzle.board,optimal.actions);if(!verified.won||verified.moves!==optimal.moves||optimal.actions.length!==optimal.moves||verified.rows.join()!==optimal.words.join())delete result.optimal;}catch{delete result.optimal;}}}catch(error){message(error instanceof Error?error.message:'Your solve is saved. Try verification again.');el('retry-submit').hidden=false;}finally{submitting=false;render();}}
function openResult(celebrate=false){
  const dialog=el<HTMLDialogElement>('result');if(!state().won||dialog.open)return;dialog.showModal();
  if(celebrate&&!reducedMotion.matches)for(let i=0;i<12;i++){
    const bit=document.createElement('i');bit.className='confetti';bit.setAttribute('aria-hidden','true');bit.style.background=['#4c8047','#e8b637','#188de4','#e8789a'][i%4];dialog.append(bit);
    const angle=i*Math.PI/6,animation=bit.animate([{opacity:0,transform:'translate(0,0) scale(0.5)'},{opacity:1,offset:0.15},{opacity:0,transform:`translate(${Math.cos(angle)*140}px,${Math.sin(angle)*110+45}px) rotate(${i*67}deg)`}],{duration:650,easing:'ease-out'});
    void animation.finished.catch(()=>{}).finally(()=>bit.remove());
  }
}
el('view-result').onclick=()=>openResult();
el<HTMLDialogElement>('result').onclose=()=>{if(state().won&&!document.querySelector('dialog[open]'))el('view-result').focus();};
for(const [dialog,button] of [['share-dialog','share'],['solution-dialog','show-solution']])el<HTMLDialogElement>(dialog).onclose=()=>{openResult();el(button).focus();};
let solutionStep=0;
function renderSolution(){const optimal=result?.optimal;if(!optimal)return;let board=[...puzzle.board];for(const action of optimal.actions.slice(0,solutionStep))board=swap(board,action);const valid=evaluate(board).validTiles,next=optimal.actions[solutionStep];el('solution-tiles').replaceChildren(...board.map((letter,i)=>{const tile=document.createElement('span');tile.className=`tile${valid[i]?' valid':''}${next&&(next.from===i||next.to===i)?' selected':''}`;tile.textContent=letter;tile.setAttribute('aria-label',`${letterName(letter)}, row ${Math.floor(i/5)+1}, column ${i%5+1}`);return tile;}));el('solution-step').textContent=`Step ${solutionStep} of ${optimal.moves}`;el('solution-action').textContent=next?`Swap ${letterName(board[next.from])} at row ${Math.floor(next.from/5)+1}, column ${next.from%5+1} with ${letterName(board[next.to])} at row ${Math.floor(next.to/5)+1}, column ${next.to%5+1}.`:optimal.words.map(word=>word.toUpperCase()).join(' · ');el<HTMLButtonElement>('solution-previous').disabled=solutionStep===0;el<HTMLButtonElement>('solution-next').disabled=solutionStep===optimal.moves;}
el('show-solution').onclick=()=>{if(!state().won||!result?.optimal)return;el<HTMLDialogElement>('result').close();solutionStep=0;renderSolution();el<HTMLDialogElement>('solution-dialog').showModal();};
function stepSolution(delta:number){if(!result?.optimal)return;const next=Math.max(0,Math.min(result.optimal.moves,solutionStep+delta));if(next===solutionStep)return;const action=result.optimal.actions[Math.min(next,solutionStep)],tiles=el('solution-tiles').children,a=tiles[action.from].getBoundingClientRect(),b=tiles[action.to].getBoundingClientRect();solutionStep=next;renderSolution();if(!reducedMotion.matches){for(const [index,x,y] of [[action.from,b.x-a.x,b.y-a.y],[action.to,a.x-b.x,a.y-b.y]])el('solution-tiles').children[index].animate([{transform:`translate(${x}px,${y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'});}if(document.activeElement instanceof HTMLButtonElement&&document.activeElement.disabled)el(solutionStep===0?'solution-next':'solution-previous').focus();}
el('solution-previous').onclick=()=>stepSolution(-1);el('solution-next').onclick=()=>stepSolution(1);
el('retry-submit').onclick=()=>void submit();el('retry-load').onclick=()=>location.reload();
type HistoryRow={day:string;moves:number;words:string[]};
function history(key=`jumble:${MODE}:history`):HistoryRow[]{try{const rows=JSON.parse(storage.get(key)||'[]');return Array.isArray(rows)?rows.filter((r:HistoryRow)=>r&&/^\d{4}-\d{2}-\d{2}$/.test(r.day)&&Number.isSafeInteger(r.moves)&&r.moves>0&&Array.isArray(r.words)&&(key.includes('swap-blank-v1')?r.words.length>=3&&r.words.length<=4&&r.words.join('').length===14:r.words.length===3)&&r.words.every(w=>typeof w==='string'&&(key.includes('swap-blank-v1')?/^[a-z]{1,5}$/:/^[a-z]{5}$/).test(w))):[];}catch{return [];}}
function currentHistories(){return [...history('jumble:swap-adjacent-v3:history'),...history('jumble:swap-blank-v1:history')].sort((a,b)=>a.day.localeCompare(b.day));}
function recordHistory(){const current=state(),rows=history(),previous=rows.find(r=>r.day===puzzle.id);if(!previous||current.moves<previous.moves)storage.set(`jumble:${MODE}:history`,JSON.stringify([...rows.filter(r=>r.day!==puzzle.id),{day:puzzle.id,moves:current.moves,words:current.rows}].sort((a,b)=>a.day.localeCompare(b.day))));}
el('history').onclick=()=>{el<HTMLDialogElement>('help-dialog').close();const rows=currentHistories(),earlier=EARLIER_MODES.flatMap(mode=>history(`jumble:${mode}:history`).slice(-30).reverse().map(row=>({...row,version:mode.endsWith('v2')?'previous word list':'original word list'})));el('history-summary').textContent=rows.length?`${rows.length} solved · ${summarizeHistory(rows,new Date().toISOString().slice(0,10)).current} day streak · ${(rows.reduce((sum,row)=>sum+row.moves,0)/rows.length).toFixed(1)} average swaps`:earlier.length?'Your earlier solves are below.':'Your first solve starts here.';el('history-list').replaceChildren(...rows.slice(-30).reverse().map(row=>{const li=document.createElement('li'),a=document.createElement('a');a.href=`/?day=${encodeURIComponent(row.day)}`;a.textContent=`${row.day} · ${row.moves} swaps${row.words.join('').length===14?' · blank day':''}`;li.append(a);return li;}));for(const row of earlier){const li=document.createElement('li');li.textContent=`${row.day} · ${row.moves} swaps · ${row.version}`;el('history-list').append(li);}el<HTMLDialogElement>('history-dialog').showModal();};
function challengeUrl(){const url=new URL(location.origin);url.searchParams.set('mode',MODE);url.searchParams.set('day',puzzle.id);return url.href;}
function shareText(){const current=state();return `JUMBLE SWAP ${puzzle.id}\n${current.moves} swaps\n${current.rows.map(word=>el<HTMLInputElement>('reveal-words').checked?word.toUpperCase():'🟩'.repeat(word.length)).join('\n')}\n${challengeUrl()}`;}
function updateShare(){el<HTMLTextAreaElement>('share-preview').value=shareText();el<HTMLAnchorElement>('share-x').href=`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText())}`;}
el('share').onclick=()=>{el<HTMLDialogElement>('result').close();el<HTMLInputElement>('reveal-words').checked=false;updateShare();el('share-status').textContent='';el<HTMLDialogElement>('share-dialog').showModal();};el('reveal-words').onchange=updateShare;
async function copyShare(text:string){try{await navigator.clipboard.writeText(text);el('share-status').textContent='Copied.';track('share');}catch{const area=el<HTMLTextAreaElement>('share-preview');area.value=text;area.focus();area.select();el('share-status').textContent='Select and copy the text above.';}}
el('copy-result').onclick=()=>void copyShare(shareText());el('copy-link').onclick=()=>void copyShare(challengeUrl());el('native-share').onclick=async()=>{try{if(navigator.share){await navigator.share({text:shareText()});track('share');}else await copyShare(shareText());}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))await copyShare(shareText());}};
el('download-result').onclick=()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#faf8f1';ctx.fillRect(0,0,1200,630);ctx.fillStyle='#15212d';ctx.font='bold 48px system-ui';ctx.fillText('JUMBLE SWAP',60,80);ctx.font='30px system-ui';ctx.fillText(`${puzzle.id} · ${state().moves} swaps`,60,140);state().rows.forEach((word,row)=>{for(let col=0;col<word.length;col++){ctx.fillStyle='#d1ebcf';ctx.fillRect(60+col*70,185+row*75,58,58);if(el<HTMLInputElement>('reveal-words').checked){ctx.fillStyle='#15212d';ctx.fillText(word[col].toUpperCase(),74+col*70,225+row*75);}}});ctx.fillStyle='#15212d';ctx.font='24px system-ui';ctx.fillText(challengeUrl(),60,570,1080);const link=document.createElement('a');link.download=`jumble-swap-${puzzle.id}.png`;link.href=canvas.toDataURL('image/png');link.click();track('share');};
const dark=storage.get('jumble:theme')==='dark'||(!storage.get('jumble:theme')&&matchMedia('(prefers-color-scheme:dark)').matches);document.body.classList.toggle('dark',dark);
function themeName(){const dark=document.body.classList.contains('dark');el('theme').setAttribute('aria-label',dark?'Use light theme':'Use dark theme');el<HTMLImageElement>('logo').src=`/assets/jumble-logo-v3${dark?'-dark':''}-720.webp`;}
themeName();el('theme').onclick=()=>{document.body.classList.toggle('dark');storage.set('jumble:theme',document.body.classList.contains('dark')?'dark':'light');themeName();if(puzzle)track('theme_toggle');};el('help').onclick=()=>el<HTMLDialogElement>('help-dialog').showModal();document.querySelectorAll<HTMLButtonElement>('dialog .close,.close-help').forEach(button=>button.onclick=()=>button.closest('dialog')?.close());
el('report-open').onclick=()=>{if(!puzzle||!dictionary)return;el<HTMLDialogElement>('help-dialog').close();el<HTMLDialogElement>('report-dialog').showModal();el<HTMLInputElement>('report-word').focus();};
el<HTMLDialogElement>('report-dialog').onclose=()=>el('help').focus();
el<HTMLFormElement>('report-form').onsubmit=async event=>{
  event.preventDefault();const button=el<HTMLButtonElement>('report-submit'),status=el('report-status');if(button.disabled)return;
  const word=el<HTMLInputElement>('report-word').value.trim().toLowerCase(),reason=el<HTMLInputElement>('report-reason').value.trim();
  if(!(blankDay()?/^[a-z]{1,5}$/:/^[a-z]{5}$/).test(word)){status.textContent=blankDay()?'Enter a word of one to five letters.':'Enter a five-letter word.';return;}
  if(dictionary.has(word)){status.textContent='That word is already accepted. Try it on the board.';return;}
  if(!reason){status.textContent='Tell us why this word should count.';return;}
  const restoreFocus=document.activeElement===button;button.disabled=true;status.textContent='Sending…';
  try{const reply=await api<{received:boolean;duplicate:boolean}>('report',{mode:MODE,puzzleId:puzzle.id,dictionaryVersion:puzzle.dictionaryVersion,word,reason});status.textContent=reply.duplicate?'You already reported this word. It is awaiting review.':'Word sent for review. This puzzle stays the same.';}
  catch(error){const messages:Record<string,string>={WORD_ALREADY_ACCEPTED:'That word is already accepted. Try it on the board.',REPORT_WORD_NOT_IN_PUZZLE:'That word needs letters outside this puzzle.',REPORT_RATE_LIMITED:'You have reported five words today. Try again tomorrow.'};status.textContent=error instanceof Error?(messages[String('code' in error?error.code:error.message)]||error.message):'Your report could not be sent. Try again.';}
  finally{button.disabled=false;if(restoreFocus&&el<HTMLDialogElement>('report-dialog').open)button.focus();}
};
type Sponsors={rows:{name:string;url:string;cents:number;rank:number}[];topCents:number;takeoverCents?:number};
function sponsorLink(sponsor:Sponsors['rows'][number]){const link=document.createElement('a'),url=new URL(sponsor.url);link.textContent=sponsor.name;if(url.protocol==='https:'&&!url.username&&!url.password){link.href=url.href;link.target='_blank';link.rel='noopener noreferrer sponsored';}return link;}
async function loadSponsors(){
  const data=await api<Sponsors>('sponsors'),spotlight=el('sponsor-spotlight'),wall=el('sponsor-wall');
  spotlight.replaceChildren();wall.replaceChildren();
  if(data.rows.length){spotlight.append('Backed by ',sponsorLink(data.rows[0]));for(const sponsor of data.rows){const row=document.createElement('article');row.append(`${sponsor.rank}. `,sponsorLink(sponsor),` · $${(sponsor.cents/100).toFixed(2)}`);wall.append(row);}}
  else{spotlight.textContent='Keep Jumble coming. Sponsor from $1.';wall.textContent='Be the first to back Jumble.';}
}
async function openSponsors(){el<HTMLDialogElement>('sponsor-dialog').showModal();track('sponsor_open');el('sponsor-wall').textContent='Loading sponsors…';try{await loadSponsors();}catch{el('sponsor-wall').textContent='Sponsors could not load. Close and reopen to try again.';}}
el('sponsors-link').onclick=()=>void openSponsors();
let quoteRequest=0;
async function updateSponsorQuote(){
  const request=++quoteRequest,takeover=el<HTMLSelectElement>('sponsor-mode').value==='takeover',url=el<HTMLInputElement>('sponsor-url').value;
  el('amount-label').hidden=takeover;el('takeover-detail').hidden=!takeover;el<HTMLInputElement>('sponsor-amount').disabled=takeover;
  const option=el<HTMLSelectElement>('sponsor-mode').options[1];option.textContent='Aim for #1';if(!takeover)return;
  el('takeover-detail').textContent=url?'Checking your link’s contribution…':'Enter your website to see the amount for #1.';if(!url)return;
  try{const data=await api<Sponsors>(`sponsors?url=${encodeURIComponent(url)}`);if(request!==quoteRequest)return;if(!Number.isSafeInteger(data.takeoverCents))throw Error('The amount could not be checked. Try again.');option.textContent=`Aim for #1 · $${(data.takeoverCents!/100).toFixed(0)}`;el('takeover-detail').textContent='Includes your link’s existing contribution. The top spot can change before payment.';}
  catch(error){if(request===quoteRequest)el('takeover-detail').textContent=error instanceof Error?error.message:'The amount could not be checked. Try again.';}
}
el('sponsor-mode').onchange=()=>void updateSponsorQuote();el('sponsor-url').onchange=()=>void updateSponsorQuote();
el<HTMLFormElement>('sponsor-form').onsubmit = async event => {
  event.preventDefault(); const form = event.currentTarget as HTMLFormElement;
  const button = form.querySelector<HTMLButtonElement>('button[type=submit]')!; button.disabled = true;
  try {
    const data = new FormData(form), mode = data.get('mode');
    const payload = {name:data.get('name'),url:data.get('url'),mode,gameMode:MODE,puzzleId:puzzle.id,returnTo:state().won?'result':'entry',...(mode==='takeover'?{}:{amount:Number(data.get('amount'))*100})};
    const fingerprint = JSON.stringify(payload);
    let pending: {fingerprint:string;submissionId:string}|null = null;
    try { pending = JSON.parse(storage.get(`jumble:${MODE}:checkout`)||'null'); } catch {}
    if (pending?.fingerprint!==fingerprint || typeof pending.submissionId!=='string') pending = {fingerprint,submissionId:crypto.randomUUID()};
    storage.set(`jumble:${MODE}:checkout`,JSON.stringify(pending));
    const response = await api<{url:string}>('checkout',{...payload,submissionId:pending.submissionId});
    const destination = new URL(response.url);
    if (destination.protocol!=='https:' || destination.hostname!=='checkout.stripe.com') throw new Error('Checkout returned an unexpected destination.');
    location.assign(destination.href);
  } catch (error) {
    el('sponsor-message').textContent = error instanceof Error?error.message:'Checkout could not start.'; button.disabled = false;
    if (error instanceof Error && 'code' in error && ['SUBMISSION_EXPIRED','CHECKOUT_EXPIRED'].includes(String(error.code))) {
      const restart=document.createElement('button');restart.type='button';restart.textContent='Start a new checkout';
      restart.onclick=()=>{storage.set(`jumble:${MODE}:checkout`,'null');restart.remove();el('sponsor-message').textContent='Ready for a new checkout. Your previous payment status has not changed.';};
      el('sponsor-message').append(restart);
    }
  }
};

document.addEventListener('keydown',event=>{if(!puzzle||document.querySelector('dialog[open]')||event.ctrlKey||event.metaKey||event.altKey)return;const target=event.target;if(!(target instanceof HTMLButtonElement)||!target.id.startsWith('tile-'))return;const i=Number(target.id.slice(5));let next=i;if(event.key==='ArrowLeft'&&i%5>0)next--;else if(event.key==='ArrowRight'&&i%5<4)next++;else if(event.key==='ArrowUp'&&i>=5)next-=5;else if(event.key==='ArrowDown'&&i<10)next+=5;else if(event.key==='Escape'){selected=null;render();message('Selection cleared.');}else return;event.preventDefault();el(`tile-${next}`).focus();});
reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches)document.getAnimations().forEach(animation=>animation.cancel());});
async function boot(){try{const params=new URLSearchParams(location.search),requested=params.get('day');puzzle=await api<Puzzle>(`puzzle${requested?`?day=${encodeURIComponent(requested)}`:''}`);if(!['swap-adjacent-v3','swap-blank-v1'].includes(puzzle.mode))throw Error('This version of Jumble is not available yet.');MODE=puzzle.mode;if(puzzle.preview){el('preview-notice').hidden=false;el('preview-notice').textContent=puzzle.preview==='synthetic-fixture'?'Preview · sample puzzle · local rankings only':'Preview · local rankings only';}puzzle.board=blankDay()?normalizeBlankBoard(puzzle.board):normalizeBoard(puzzle.board);if(blankDay()){document.querySelector('.intro p')!.textContent='Swap neighbors. Use blanks to split words.';el('help-heading').textContent='Make every word count.';el('help-rules').textContent='A blank is a space, not a letter. Every word must count. A and I can stand alone. AT□ON makes AT + ON. Each word must be different.';el<HTMLInputElement>('report-word').pattern='[A-Za-z]{1,5}';el<HTMLInputElement>('report-word').minLength=1;}const r=await fetch(`/data/swap-words-${encodeURIComponent(puzzle.dictionaryVersion)}.json`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('The word list could not load. Try again.');const lexicon=await r.json();if(lexicon.version!==puzzle.dictionaryVersion||!Array.isArray(lexicon.words)||!lexicon.words.every((w:unknown)=>typeof w==='string'&&(blankDay()?/^[a-z]{1,5}$/:/^[a-z]{5}$/).test(w)))throw Error('The word list could not be verified.');dictionary=new Set(lexicon.words);save={version:1,mode:MODE,puzzleId:puzzle.id,dictionaryVersion:puzzle.dictionaryVersion,initialBoard:puzzle.board.join(''),actions:[]};try{const restored=JSON.parse(storage.get(saveKey())||'null');if(restored?.version===1&&restored.mode===MODE&&restored.puzzleId===puzzle.id&&restored.dictionaryVersion===puzzle.dictionaryVersion&&restored.initialBoard===puzzle.board.join('')&&Array.isArray(restored.actions)){replay(puzzle.board,restored.actions);save.actions=restored.actions;}}catch{}const updated=!storage.get(saveKey())&&EARLIER_MODES.some(mode=>!!storage.get(`jumble:${mode}:${puzzle.id}`));if(updated)persist();el('day').textContent=`DAILY · ${puzzle.id}`;el('game').setAttribute('aria-busy','false');render();message(updated?'Puzzle updated. Start fresh.':'');track('puzzle_view');updateTodayLink();if(state().won){openResult();void submit();}if(['thanks','cancelled'].includes(params.get('sponsor')||'')){storage.set(`jumble:${MODE}:checkout`,'null');el('sponsor-return').hidden=false;el('sponsor-return').textContent=params.get('sponsor')==='thanks'?'Thanks. Your listing appears after payment confirmation.':'Checkout cancelled. Your board is saved.';}}catch(error){message(error instanceof Error?error.message:'Jumble could not load.');el('retry-load').hidden=false;}}
let rolloverTimer:number;
function updateTodayLink(){clearTimeout(rolloverTimer);el('today-link').hidden=!todayLinkVisible(puzzle.id);rolloverTimer=window.setTimeout(updateTodayLink,86400000-Date.now()%86400000+50);}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&puzzle)updateTodayLink();});
void boot();
void loadSponsors().catch(()=>{el('sponsor-spotlight').textContent='Sponsors are unavailable right now.';});
